services:
  web:
    image: ${DOCKER_REGISTRY-}omcleanarch.api
    build:
      context: .
      dockerfile: backend/Web/Dockerfile
    ports:
      - 7800:7800
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - postgres

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "8081:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    volumes:
      - ./seq-data:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - "18888:18888" # Dashboard UI
      - "18889:18889" # OTLP gRPC
      - "18890:18890" # OTLP HTTP

volumes:
  pgdata:
