services:
  cleanarch:
    image: zormax/cleanarch:latest
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    ports:
      - 7700:7800
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "8081:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    volumes:
      - ./seq-data:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "127.0.0.1/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopw
      ME_CONFIG_MONGODB_URL: mongodb://root:mongopw@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 5

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - "18888:18888" # Dashboard UI
      - "18889:18889" # OTLP gRPC
      - "18890:18890" # OTLP HTTP

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8083:8081"
    depends_on:
      - redis

  search-svc:
    image: zormax/search-svc:latest
    build:
      context: .
      dockerfile: other-services/SearchService/Dockerfile
    ports:
      - 7704:7800
    env_file:
      - .env.docker
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  identity-svc:
    image: zormax/identity-svc:latest
    build:
      context: .
      dockerfile: other-services/IdentityService/Dockerfile
    ports:
      - 5001:7800
    env_file:
      - .env.docker
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      postgres:
        condition: service_healthy

  gateway-svc:
    image: zormax/gateway-svc:latest
    build:
      context: .
      dockerfile: other-services/GatewayService/Dockerfile
    ports:
      - 7706:7800
    env_file:
      - .env.docker
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

volumes:
  mongodata:
